version: '3'
services:
  db:
    network_mode: host
    image: postgres
    restart: always
    expose: 
      - 5432
    environment:
      POSTGRES_PASSWORD: test
  api:
    build: .
    restart: always
    depends_on: 
      - db
    network_mode: host
    expose: [80]
    volumes: 
      - ./src:/app